# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from game_server.models.base_model_ import Model
from game_server import util


class Game(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, tag=None, status=None):  # noqa: E501
        """Game - a model defined in OpenAPI

        :param id: The id of this Game.  # noqa: E501
        :type id: int
        :param name: The name of this Game.  # noqa: E501
        :type name: str
        :param tag: The tag of this Game.  # noqa: E501
        :type tag: str
        :param status: The status of this Game.  # noqa: E501
        :type status: str
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'tag': str,
            'status': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'tag': 'tag',
            'status': 'status'
        }

        self._id = id
        self._name = name
        self._tag = tag
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Game':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Game of this Game.  # noqa: E501
        :rtype: Game
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Game.


        :return: The id of this Game.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Game.


        :param id: The id of this Game.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Game.


        :return: The name of this Game.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Game.


        :param name: The name of this Game.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def tag(self):
        """Gets the tag of this Game.


        :return: The tag of this Game.
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this Game.


        :param tag: The tag of this Game.
        :type tag: str
        """

        self._tag = tag

    @property
    def status(self):
        """Gets the status of this Game.


        :return: The status of this Game.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Game.


        :param status: The status of this Game.
        :type status: str
        """

        self._status = status
